source 'https://rubygems.org'

gemspec

group :development do
  gem 'bundler'
  gem 'byebug', require: false
  gem 'guard', require: false
  gem 'mysql2'
end

group :test do
  gem 'mocha'
  gem 'rake'
  gem 'rspec'
  gem 'simplecov'
  gem 'sqlite3'
end

