source 'https://rubygems.org'

gemspec

gem 'bundler', :group => :development
gem 'byebug', :group => :test
gem 'mocha', :group => :test
gem 'rspec', :group => :test
gem 'simplecov', :group => :test
gem 'sqlite3', :group => :development
gem 'mysql2', :group => :development

