#!/usr/bin/env rake
require 'bundler'
require "bundler/gem_tasks"
require "rspec/core/rake_task"

task :default => :spec

desc "Run specs"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts =%w{--color --format progress}
  task.pattern = 'spec/*_spec.rb'
end

task :rdoc do
  system("rdoc rdoc lib")
end

desc "Build RPM and dependencies (intended for University of Idaho IBEST internal use)"
task :rpm_deps => [:build] do
  require 'erb'
  require 'yaml'

  build_rpms({
    'bookie_accounting' => {
      :is_app => true,
      :has_binaries => true,
      :gem_file => "bookie_accounting-#{Bookie::VERSION}.gem",
      :license => 'MIT',
      :skip_deps => Set.new(['sqlite3']),
    },
    'spreadsheet' => {
      :has_binaries => true,
      :license => 'GPL3',
    },
    'ruby-ole' => {
      :license => 'MIT',
    },
    'pacct' => {
      :license => 'MIT',
    },
  })
end

def find_gem_file(gem_name)
  Dir.glob("#{gem_name}-*.gem")[0]
end
 
def build_rpms(modules_to_build)
  this_dir = Dir.pwd
  pkg_dir = File.join(this_dir, 'pkg')

  home_dir = Etc.getpwuid.dir

  rpmbuild_dir = File.join(home_dir, 'rpmbuild')
  spec_dir = File.join(rpmbuild_dir, 'SPECS')
  src_dir = File.join(rpmbuild_dir, 'SOURCES')
  rpm_dir = File.join(rpmbuild_dir, 'RPMS')

  [spec_dir, src_dir].each do |dir|
    FileUtils.mkdir_p(dir)
  end

  #To do: packaging for Ruby versions other than 1.8
  template = ERB.new(File.read('rpm/spec_template.erb'))
  lockfile = Bundler::LockfileParser.new(Bundler.read_file("Gemfile.lock"))
  lockfile.specs.each do |spec|
    extra_data = modules_to_build[spec.name]
    next unless extra_data

    gem_name = spec.name
    version = spec.version

    puts gem_name

    #Has the RPM already been built?
    next if Dir.glob(File.join(rpm_dir, "*/(rubygem-)?#{gem_name}-#{version}-*.rpm")).length > 0
    
    ruby_version = RUBY_VERSION.split('.')[0 .. 1].join('.')

    #Get the gem.
    Dir.chdir(src_dir)
    gem_file = extra_data[:gem_file]
    if gem_file
      FileUtils.cp(File.join(pkg_dir, gem_file), '.')
    else
      gem_file = find_gem_file(gem_name)
      #To do: handle old versions of gems existing in src_dir
      system("gem fetch #{gem_name} -v #{version}") unless gem_file && File.exists?(gem_file)
      gem_file ||= find_gem_file(gem_name)
    end
    fail "Unable to find gem file for #{gem_name}" unless gem_file
    gem = File.basename(gem_file, '.gem')
    s = YAML.load(`gem spec #{gem_file}`)

    #Build the RPM spec.
    Dir.chdir(spec_dir)
    if s.licenses.length > 0
      license = s.licenses.join(' AND ')
    else
      license = extra_data[:license]
    end
    url = s.homepage
    summary = s.summary
    description = s.description
    requires = []
    build_requires = []
    s.dependencies.each do |dep|
      case dep.type
      when :development
        build_requires.push(dep)
      else
        requires.push(dep)
      end
    end
    requires.map!{ |r| "rubygem-#{r.name}" }
    
    is_app = extra_data[:is_app]
    has_binaries = extra_data[:has_binaries]

    if is_app
      spec_filename = "#{gem_name}.spec"
    else
      spec_filename = "rubygem-#{gem_name}.spec"
    end
    spec_filename = File.join(spec_dir, spec_filename)

    File.open(spec_filename, "w") do |file|
      template_filename = File.join(this_dir, "rpm/#{gem_name}.spec.erb")
      if File.exists?(template_filename)
         file.write(ERB.new(File.read(template_filename)).result(binding))
      else
        file.write(template.result(binding))
      end
    end

    msg = `rpmbuild -ba #{spec_filename}`
    unless $?.success?
      puts msg
      exit 1
    end
  end

  Dir.chdir(this_dir)
end

