#!/usr/bin/env rake
require 'bundler'
require "bundler/gem_tasks"
require "rspec/core/rake_task"

require 'find'

task :default => :spec

desc "Run specs"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts =%w{--color --order rand --format progress}
  paths = []
  Find.find('spec') do |path|
    if File.directory?(path)
      paths << "#{path}/*_spec.rb"
    end
  end
  task.pattern = paths.join(" ")
end

task :rdoc do
  system("rdoc rdoc lib")
end

