require "bundler/gem_tasks"
require "rspec/core/rake_task"

task :default => :spec

desc "Run specs"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts =%w{--color --format progress}
  task.pattern = 'spec/*_spec.rb'
end

task :docs do
  #To do: figure out why rdoc needs this deleted to process all files.
  FileUtils.rm_r('doc')
  system('rdoc --exclude spec --exclude snapshot --exclude rpm --exclude rpmbuild --exclude config')
end

